# playbook.yaml
# playbook extraido de
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_intro.html

---
- name: Update web servers
  hosts: webservers
  remote_user: root

  tasks:
  - name: Ensure apache is at the latest version
    ansible.builtin.yum: # yum module
      name: httpd
      state: latest

  - name: Write the apache config file
    ansible.builtin.template: # template module
      src: /srv/httpd.j2
      dest: /etc/httpd.conf

- name: Update db servers
  hosts: databases
  remote_user: root

  tasks:
  - name: Ensure postgresql is at the latest version
    ansible.builtin.yum:
      name: postgresql
      state: latest

  - name: Ensure that postgresql is started
    ansible.builtin.service: # service module
      name: postgresql
      state: started